###

POST http://localhost:3000/users?name=Jose
Content-Type: application/json
fizz: buzz 

{
  "name": "Carlos Eduardo",
  "number": "22998249847",
  "email":"c.eduardopaes@exemplo.com",
  "password":"SenhaBernardo"
}

###

GET http://localhost:3000/ping

###

GET  http://localhost:3000/hello

###

PATCH http://localhost:3000/users?name=Jose

###

PUT http://localhost:3000/users?name=Jose

###

//=============================== HTTPS ===========================

###

GET https://localhost:3000/sample

###